#
# File:      $RCSfile: viewer.viewer.dutch,v $
# Version:   $Revision: 1.7.2.4.2.1.6.4 $
# Revised:   $Date: 2013/01/07 08:18:37 $
#            $Author: ma-ran $
#
# Created:   2003-06-05
# Project:   Neptune
#
#
# Description: Translation of strings for the combined web client
#              and CD viewer
#
# Copyright (c) 2003 Sectra Imtec AB, Linkoping, Sweden.
# All rights reserved.
#

msgid "DISCLAIMER General disclaimer"
msgstr "BELANGRIJKE EXONERATIECLAUSULE EN WAARSCHUWING  Als gebruiker van deze toepassing erken ik het volgende:

Defecten of storingen in computerhardware of -software, evenals gebruikersfouten, kunnen de gegevens die afgeleid zijn uit deze toepassing beschadigen.

Sectra, als producent van deze toepassing, kan de nauwkeurigheid van de informatie of de resultaten die verkregen zijn met deze toepassing niet garanderen, en wijst elke aansprakelijkheid hiervoor af.

Als gebruiker van deze toepassing moet ik te allen tijde alle gegevens of aanbevelingen die verkregen zijn met deze toepassing onafhankelijk verifiëren voordat deze toegepast worden op mensen. "

msgid "DISCLAIMER Printing disclaimer"
msgstr "WAARSCHUWING!
DE KWALITEIT VAN DEZE BEELDAFDRUK KAN ONVOLDOENDE ZIJN.
DAAROM MAG DEZE AFDRUK NIET GEBRUIKT WORDEN VOOR DIAGNOSTISCHE DOELEINDEN. "

msgid "%"
msgstr "%"

msgid "&Angle"
msgstr "&Hoek"

msgid "&Annotations"
msgstr "&Annotaties "

msgid "&Anonymized"
msgstr "&Geanonimiseerd "

msgid "&Calibration"
msgstr "&Kalibratie"

msgid "&Circle"
msgstr "&Cirkel"

msgid "&Compression factor:"
msgstr "&Compressiefactor: "

msgid "&Confirm new password:"
msgstr "&Bevestig het nieuwe wachtwoord:"

msgid "&Delete"
msgstr "&Wissen"

msgid "&Distance"
msgstr "&Afstand"

msgid "Distance measurement:"
msgstr "Afstandsmeting:"

msgid "&Edit"
msgstr "&Bewerken"

msgid "&Enterprise wide search"
msgstr "&Uitgebreid zoeken systeem"

msgid "&File"
msgstr "&Bestand"

msgid "&Help"
msgstr "&Help"

msgid "&Hide annotations"
msgstr "&Annotaties verbergen"

msgid "&Hide scanogram"
msgstr "&Scanogram verbergen"

msgid "&Image information"
msgstr "&Beeldinformatie"

msgid "&Line"
msgstr "&Lijn"

msgid "&Localizer"
msgstr "&Localizer"

msgid "&Minimum"
msgstr "&Minimum"

msgid "&New password:"
msgstr "&Nieuw wachtwoord:"

msgid "&Old password:"
msgstr "&Oud wachtwoord: "

msgid "&Partition"
msgstr "&Onderverdeling"

msgid "&Password:"
msgstr "&Wachtwoord:"

msgid "&Point"
msgstr "&Punt"

msgid "&Polyline"
msgstr "&Meerdere lijnen"

msgid "&Requests"
msgstr "&Verzoeken"

msgid "&Reset calibration"
msgstr "Kalibratie &herstellen"

msgid "&Reset"
msgstr "&Herstellen"

msgid "&Search criteria:"
msgstr "&Zoekcriteria: "

msgid "&Show annotations"
msgstr "Annotaties &tonen"

msgid "&Show scanogram"
msgstr "Scanogram &tonen"

msgid "&Text"
msgstr "&Tekst"

msgid "&User name:"
msgstr "&Gebruikersnaam: "

msgid "&View"
msgstr "&Weergave"

msgid "(This warning can be turned off in the compression settings dialog by selecting custom netwok type and unchecking the performance warning checkbox.)"
msgstr "(Deze waarschuwing kan uitgeschakeld worden in het dialoogvenster met compressie-instellingen door aangepast netwerktype te kiezen en het selectievakje uitvoeringswaarschuwing uit te vinken.) "

msgid "+"
msgstr "+"

msgid "-"
msgstr "-"

msgid "----- Detailed statistics -----"
msgstr "----- Gedetailleerde statistische gegevens -----"

msgid "----- Estimated performance -----"
msgstr "----- Geschatte prestatie -----"

msgid "----- Recommended compression settings -----"
msgstr "----- Aanbevolen compressie-instellingen -----"

msgid "/"
msgstr "/"

msgid "1 by 1 partition"
msgstr "1 bij 1 onderverdeling"

msgid "1 by 2 partition"
msgstr "1 bij 2 onderverdeling"

msgid "1 by 3 partition"
msgstr "1 bij 3 onderverdeling"

msgid "1 day"
msgstr "1 dag"

msgid "1 month"
msgstr "1 maand"

msgid "1 week"
msgstr "1 week"

msgid "1 year"
msgstr "1 jaar"

msgid "180°"
msgstr "180°"

msgid "1:1"
msgstr "1:1"

msgid "1x1"
msgstr "1x1"

msgid "1x2"
msgstr "1x2"

msgid "1x3"
msgstr "1x3"

msgid "2 by 1 partition"
msgstr "2 bij 1 onderverdeling"

msgid "2 by 2 partition"
msgstr "2 bij 2 onderverdeling"

msgid "2 by 3 partition"
msgstr "2 bij 3 onderverdeling"

msgid "2 days"
msgstr "2 dagen"

msgid "2 months"
msgstr "2 maanden"

msgid "2 weeks"
msgstr "2 weken"

msgid "270°"
msgstr "270°"

msgid "2x1"
msgstr "2x1"

msgid "2x2"
msgstr "2x2"

msgid "2x3"
msgstr "2x3"

msgid "3 by 1 partition"
msgstr "3 bij 1 onderverdeling"

msgid "3 by 2 partition"
msgstr "3 bij 2 onderverdeling"

msgid "3 by 3 partition"
msgstr "3 bij 3 onderverdeling"

msgid "3 days"
msgstr "3 dagen"

msgid "3 months"
msgstr "3 maanden"

msgid "3 weeks"
msgstr "3 weken"

msgid "3x1"
msgstr "3x1"

msgid "3x2"
msgstr "3x2"

msgid "3x3"
msgstr "3x3"

msgid "4 days"
msgstr "4 dagen"

msgid "4x4"
msgstr "4x4"

msgid "5 days"
msgstr "5 dagen"

msgid "6 days"
msgstr "6 dagen"

msgid "6 months"
msgstr "6 maanden"

msgid "90°"
msgstr "90°"

msgid "<Custom>"
msgstr "<Custom>"

msgid "A forced logout from the workstation has occurred since the user logged in to another workstation."
msgstr "Op dit werkstation heeft een gedwongen afmelding plaatsgevonden omdat de gebruiker zich heeft aangemeld op een ander werkstation. "

msgid "A logout from the workstation has occurred due to a long time period without any action."
msgstr "Op dit werkstation heeft een afmelding plaatsgevonden vanwege een lange periode van inactiviteit. "

msgid "A worklist with this name already exists. Please choose another name."
msgstr "Er bestaat al een werklijst met deze naam.
Kies a.u.b. een andere naam. "

msgid "A&rea"
msgstr "Ge&bied"

msgid "AC: [num_avg,%g]"
msgstr "AC: [num_avg,%g]"

msgid "About"
msgstr "Info"

msgid "About..."
msgstr "Info..."

msgid "Accession number (Request ID)"
msgstr "Accessionnummer (Aanvraag nummer) "

msgid "Accession number"
msgstr "Accessionnummer"

msgid "Add"
msgstr "Toevoegen"

msgid "Agreement"
msgstr "Overeenkomst "

msgid "All files"
msgstr "Alle bestanden"

msgid "All required information is not entered. Report is not saved to WISE."
msgstr "Niet alle benodigde informatie is ingevoerd. Het verslag wordt niet opgeslagen op de WISE-server. " 

msgid "An error has occured during the search, please press the 'Refresh' button in the search dialog."
msgstr "Er is een fout opgetreden tijdens het zoeken; druk op de knop 'Vernieuwen' in het zoekdialoogvenster. "

msgid "An error occured during the search, please try again."
msgstr "Er is een fout opgetreden tijdens het zoeken, probeer het opnieuw. "

msgid "An unspecified error occured, see the logfile for details."
msgstr "Er is een niet-gespecificeerde fout opgetreden, zie het logbestand voor informatie. "

msgid "Angle"
msgstr "Hoek"

msgid "Annotate"
msgstr "Annoteren"

msgid "Anon"
msgstr "Anon."

msgid "Anonymized image info"
msgstr "Geanonimiseerde beeldinfo"

msgid "Apply Presentation State"
msgstr "Presentatiestatus toepassen"

msgid "Apply image's own window setting"
msgstr "Eigen vensterinstelling van het beeld toepassen"

msgid "Apply local window setting"
msgstr "Lokale vensterinstelling toepassen"

msgid "Apply presentation state"
msgstr "Presentatiestatus toepassen"

msgid "Archive status"
msgstr "Archief status"

msgid "Archived"
msgstr "Gearchiveerd"

msgid "Area"
msgstr "Oppervlakte"

msgid "Automatically show all tool controls"
msgstr "Automatisch alle toolregelingen tonen "

msgid "Automatically show the scroll control"
msgstr "Automatisch de schuifregeling tonen "

msgid "Automatically show the window/level control"
msgstr "Automatisch de venster/niveau-regeling tonen "

msgid "Automatically show the zoom control"
msgstr "Automatisch de zoomregeling tonen "

msgid "Average time:"
msgstr "Gemiddelde tijd: "

msgid "Begins with"
msgstr "begint met"

msgid "Black"
msgstr "Zwart"

msgid "Body part"
msgstr "Lichaamsdeel"

msgid "Bone"
msgstr "Bot"

msgid "Bounce selected range"
msgstr "Bounce geselecteerd bereik"

msgid "Bounce"
msgstr "Bounce"

msgid "Bytes"
msgstr "Bytes"

msgid "C: [center,%7.1f], W: [width,%7.1f]"
msgstr "C: [center,%7.1f], W: [width,%7.1f]"

msgid "CE_STATEMENT"
msgstr "Deze medische apparatuur voldoet aan de voorwaarden
van de Richtlijn voor medische apparatuur 93/42/EEC in het 
oorspronkelijke land van de meldingsinstantie die over de 
apparatuur gaat."

msgid "CE_NUMBER"
msgstr "0344"

msgid "CONTACT_INFO_COMPANY"
msgstr "Sectra AB"

msgid "CONTACT_INFO_COUNTRY"
msgstr "SWEDEN"

msgid "CONTACT_INFO_STREET_ADDRESS"
msgstr "Teknikringen 20"

msgid "CONTACT_INFO_ZIP_CODE_AND_CITY"
msgstr "SE-583 30 Linköping"

msgid "COPYRIGHT_TEXT"
msgstr "Alle rechten zijn voorbehouden. Reproductie of transmissie, geheel of gedeeltelijk, in enigerlei vorm of op enigerlei wijze, elektronisch, mechanisch of anderszins, is verboden zonder schriftelijke toestemming van de eigenaar van het auteursrecht."

msgid "Cable modem (1.5 Mb/s)"
msgstr "Kabelmodem (1.5 Mb/s) "

msgid "Cable modem (5 Mb/s)"
msgstr "Kabelmodem (5 Mb/s) "

msgid "Calib"
msgstr "Kalibr"

msgid "Calibrate image"
msgstr "Beeld kaliberen "

msgid "Calibration"
msgstr "Kalibratie"

msgid "&Cancel"
msgstr "&Annuleren"

msgid "Cancel"
msgstr "Annuleren"

msgid "Cancelling test, please wait..."
msgstr "Test wordt geannuleerd, even geduld a.u.b. ... "

msgid "Case history"
msgstr "Casusgeschiedenis"

msgid "Change Password"
msgstr "Verander wachtwoord"

msgid "Change password..."
msgstr "Verander wachtwoord..."

msgid "Change the password"
msgstr "Wachtwoord veranderen "

msgid "Change"
msgstr "Veranderen"

msgid "Check for updates"
msgstr "Controleren op updates"

msgid "Check for updates on the Image Viewer web site."
msgstr "Controleer op updates op website van de Beeldviewer. "

msgid "Cine Tool"
msgstr "Cine-tool"

msgid "Cine bounce"
msgstr "Cine-bounce"

msgid "Cine loop to next key image"
msgstr "Cine afspelen naar volgende sleutelbeeld"

msgid "Cine loop to previous key image"
msgstr "Cine afspelen naar vorige sleutelbeeld"

msgid "Cine loop"
msgstr "Cine-loop"

msgid "Cine to next"
msgstr "Cine naar volgende"

msgid "Cine to previous"
msgstr "Cine naar vorige"

msgid "Circle"
msgstr "Cirkel"

msgid "Clear presentation"
msgstr "Presentatie wissen "

msgid "Clear the current presentation"
msgstr "Huidige presentatie wissen "

msgid "Clear"
msgstr "Wissen"

msgid "Click this button to reset the compression factor to the default value."
msgstr "Klik op deze knop om de compressiefactor naar de standaardwaarde te herstellen. "

msgid "Coagulated blood"
msgstr "Gecoaguleerd bloed"

msgid "Comments"
msgstr "Opmerkingen"

msgid "Compr"
msgstr "Compr."

msgid "Compression Settings"
msgstr "Compressie-instellingen"

msgid "Compression settings..."
msgstr "Compressie-instellingen..."

msgid "Compression: 1:[compression,%.0f]"
msgstr "Compressie: 1:[compression,%.0f]"

msgid "Configure the image compression"
msgstr "Beeldcompressie configureren "

msgid "Contact information:"
msgstr "Productie-adres:"

msgid "Contains"
msgstr "bevat"

msgid "Contrast: [contrast]"
msgstr "Contrast: [contrast]"

msgid "Control"
msgstr "Regeling"

msgid "Copy image to clipboard"
msgstr "Beeld naar klembord kopiëren"

msgid "Copy to clipboard"
msgstr "Naar klembord kopiëren"

msgid "Copy"
msgstr "Kopiëren"

msgid "Create a magnifying glass"
msgstr "Vergrootglas creëren "

msgid "Creator"
msgstr "Aangemaakt door"

msgid "Crop image"
msgstr "Beeld inkaderen"

msgid "Crop"
msgstr "Inkaderen"

msgid "Ctrl+1"
msgstr "Ctrl+1"

msgid "Ctrl+2"
msgstr "Ctrl+2"

msgid "Ctrl+3"
msgstr "Ctrl+3"

msgid "Ctrl+4"
msgstr "Ctrl+4"

msgid "Ctrl+Shift+1"
msgstr "Ctrl+Shift+1"

msgid "Ctrl+Shift+2"
msgstr "Ctrl+Shift+2"

msgid "Ctrl+Shift+3"
msgstr "Ctrl+Shift+3"

msgid "Ctrl+Shift+4"
msgstr "Ctrl+Shift+4"

msgid "Ctrl+Shift+6"
msgstr "Ctrl+Shift+6"

msgid "Ctrl+Shift+9"
msgstr "Ctrl+Shift+9"

msgid "Ctrl+Shift+l"
msgstr "Ctrl+Shift+l"

msgid "Ctrl+Shift+r"
msgstr "Ctrl+Shift+r"

msgid "Ctrl+Shift+z"
msgstr "Ctrl+Shift+z"

msgid "Ctrl+Space"
msgstr "Ctrl+Spatie"

msgid "Ctrl+a"
msgstr "Ctrl+a"

msgid "Ctrl+b"
msgstr "Ctrl+b"

msgid "Ctrl+c"
msgstr "Ctrl+c"

msgid "Ctrl+e"
msgstr "Ctrl+e"

msgid "Ctrl+f"
msgstr "Ctrl+f"

msgid "Ctrl+g"
msgstr "Ctrl+g"

msgid "Ctrl+h"
msgstr "Ctrl+h"

msgid "Ctrl+i"
msgstr "Ctrl+i"

msgid "Ctrl+k"
msgstr "Ctrl+k"

msgid "Ctrl+l"
msgstr "Ctrl+l"

msgid "Ctrl+p"
msgstr "Ctrl+p"

msgid "Ctrl+r"
msgstr "Ctrl+r"

msgid "Ctrl+s"
msgstr "Ctrl+s"

msgid "Ctrl+w"
msgstr "Ctrl+w"

msgid "Ctrl+z"
msgstr "Ctrl+z"

msgid "Cut out part of image"
msgstr "Gedeelte van beeld wegsnijden "

msgid "DICOM Package"
msgstr "DICOM Pakket"

msgid "DICOM PS"
msgstr "DICOM PS"

msgid "DICOM Study ID"
msgstr "DICOM Instance UID"

msgid "DSL (256 kb/s)"
msgstr "DSL (256 kb/s)"

msgid "Data directory:"
msgstr "Gegevensdirectory: "

msgid "Date and time"
msgstr "Datum en tijd"

msgid "Date"
msgstr "Datum"

msgid "day"
msgstr "dag"

msgid "days"
msgstr "dagen"

msgid "Decrease the image size"
msgstr "Beeldgrootte verkleinen"

msgid "Description"
msgstr "Beschrijving"

msgid "Deviation:"
msgstr "Afwijking:"

msgid "Disable hardware acceleration"
msgstr "Hardwareversnelling uitschakelen"

msgid "Disable the use of hardware acceleration for image display"
msgstr "Gebruik van hardwareversnelling voor beeldweergave uitschakelen "

msgid "Disable"
msgstr "Uitschakelen"

msgid "Display next image in stack/collection"
msgstr "Volgende beeld in stack/verzameling tonen"

msgid "Display next stack section according to selected tile"
msgstr "Volgende stack-gedeelte tonen volgens geselecteerde tegel"

msgid "Display previous image in stack/collection"
msgstr "Vorige beeld in stack/verzameling tonen"

msgid "Display previous stack section according to selected tile"
msgstr "Vorige stack-gedeelte tonen volgens geselecteerde tegel"

msgid "Display the full popup menu"
msgstr "Volledige popup-menu tonen"

msgid "Distance"
msgstr "Afstand"

msgid "Do not show any tool controls automatically"
msgstr "Toolregelingen niet automatisch tonen "

msgid "Do not show this warning again"
msgstr "Deze waarschuwing niet opnieuw tonen "

msgid "Do you really want to remove this worklist?"
msgstr "Weet u zeker dat u deze werklijst wilt verwijderen? "

msgid "Do you want to go to the Image Viewer web site to check for updates?"
msgstr "Wilt u naar de website van de Beeldviewer gaan om te controleren of er updates zijn? "

msgid "Doctor"
msgstr "Arts"

msgid "Document window"
msgstr "Documentvenster "

msgid "Draw circle"
msgstr "Cirkel tekenen"

msgid "Draw line"
msgstr "Lijn tekenen"

msgid "Draw point"
msgstr "Punt tekenen"

msgid "Draw polyline"
msgstr "Meerdere lijnen tekenen"

msgid "E&xit"
msgstr "Af&sluiten"

msgid "ECG curve"
msgstr "ECG-curve"

msgid "Edge enh."
msgstr "Contourverst."

msgid "Edge enhance"
msgstr "Contourversterking"

msgid "End"
msgstr "Einde"

msgid "Enlarge the image"
msgstr "Beeld vergroten"

msgid "Enter the amount of data to fetch, from 1 to 100% of the compressed code stream. A higher percentage gives higher quality but will take longer to fetch."
msgstr "Voer de hoeveelheid op te halen gegevens in, van 1 tot 100% van de gecomprimeerde code-stream.  Een hoger percentage levert een hogere kwaliteit op, maar het ophalen duurt langer. "

msgid "Equal"
msgstr "is"

msgid "Error"
msgstr "Fout"

msgid "Estimated time:"
msgstr "Geschatte tijd: "

msgid "Exam code"
msgstr "Onderzoekscode "

msgid "Examination age"
msgstr "Ouderdom van onderzoek"

msgid "Examination ID"
msgstr "Onderzoeksnr."

msgid "Examination Properties"
msgstr "Eigenschappen van onderzoek"

msgid "Examination code"
msgstr "Onderzoekscode "

msgid "Examination database ID"
msgstr "Databasenr. onderzoek"

msgid "Examination number"
msgstr "Onderzoeksnr."

msgid "Examination properties..."
msgstr "Eigenschappen van onderzoek..."

msgid "Examinations"
msgstr "Onderzoeken"

msgid "Exit and logout"
msgstr "Afsluiten en afmelden "

msgid "Exit"
msgstr "Afsluiten"

msgid "Exported by"
msgstr "Geëxporteerd door "

msgid "F1"
msgstr "F1"

msgid "F10"
msgstr "F10"

msgid "F11"
msgstr "F11"

msgid "F12"
msgstr "F12"

msgid "F2"
msgstr "F2"

msgid "F3"
msgstr "F3"

msgid "F4"
msgstr "F4"

msgid "F5"
msgstr "F5"

msgid "F6"
msgstr "F6"

msgid "F7"
msgstr "F7"

msgid "F8"
msgstr "F8"

msgid "F9"
msgstr "F9"

msgid "F: [filter]"
msgstr "F: [filter]"

msgid "Failed to add external user. Contact your system administrator for help."
msgstr "Kon externe gebruiker niet toevoegen.  Neem contact op met uw systeembeheerder voor hulp. "

msgid "Failed to connect to IDS5/net server."
msgstr "Verbinding maken met de IDS5/net server is mislukt."

msgid "Failed to initiate archive retrieval of the selected examination(s). Please wait a while and then press the '%s' button in order to synchronize with the server."
msgstr "Ophalen uit archief van de geselecteerde onderzoek(en) is mislukt.  Wacht even en druk vervolgens op de '%s'-knop om te synchroniseren met de server. "

msgid "Failed"
msgstr "Mislukt"

msgid "False"
msgstr "Onwaar"

msgid "Fetching presentation examinations..."
msgstr "Bezig met ophalen presentatie onderzoeken... "

msgid "Fetching presentation..."
msgstr "Bezig met ophalen presentatie... "

msgid "Fetching reports and scanned documents..."
msgstr "Bezig met ophalen van verslagen en gescande documenten... "

msgid "Fetching series..."
msgstr "Bezig met ophalen van serie... "

msgid "Fetching the full DICOM image without compression might take considerable time."
msgstr "Het ophalen van het volledige DICOM-beeld zonder compressie kan aanzienlijke tijd duren. "

msgid "First"
msgstr "Eerste"

msgid "Fit"
msgstr "Passen"

msgid "Flip horizontal"
msgstr "Horizontaal omklappen"

msgid "Flip image in horizontal direction"
msgstr "Beeld horizontaal omklappen"

msgid "Flip image in vertical direction"
msgstr "Beeld verticaal omklappen"

msgid "Flip vertical"
msgstr "Verticaal omklappen"

msgid "Flip"
msgstr "Omklappen"

msgid "FoV: [fov,%g] mm"
msgstr "FoV: [fov,%g] mm"

msgid "Frame positioning wheel"
msgstr "Framepositioneringswiel"

msgid "Frame: "
msgstr "Frame: "

msgid "Full DICOM quality"
msgstr "Volledige DICOM-kwaliteit"

msgid "Full screen"
msgstr "Volledig scherm"

msgid "Full"
msgstr "Volledig"

msgid "Gantry: [gantry,%g]°"
msgstr "Schraag: [gantry,%g]° "

msgid "Get settings from a DICOM presentation state"
msgstr "Instellingen van een DICOM-presentatiestatus krijgen"

msgid "Go to first image in stack"
msgstr "Ga naar eerste beeld in de stack"

msgid "Go to last image in stack"
msgstr "Ga naar laatste beeld in de stack"

msgid "Go to next key image"
msgstr "Ga naar volgende sleutelbeeld"

msgid "Go to next"
msgstr "Ga naar volgende"

msgid "Go to previous key image"
msgstr "Ga naar vorige sleutelbeeld"

msgid "Go to previous"
msgstr "Ga naar vorige"

msgid "Go to the Image Viewer web site"
msgstr "Ga naar de website van de Beeldviewer "

msgid "Greater than"
msgstr "groter dan"

msgid "Grey brain substance"
msgstr "Grijze hersensubstantie"

msgid "Help"
msgstr "Help"

msgid "Hide DICOM &overlays"
msgstr "DICOM-&overlays verbergen"

msgid "Hide DICOM overlays"
msgstr "DICOM-overlays verbergen"

msgid "Hide all available localizer lines, including crosshair marker"
msgstr "Alle beschikbare localizer-lijnen verbergen, inclusief kruiscursor"

msgid "Hide all controls"
msgstr "Alle regelingen verbergen "

msgid "Hide annotations"
msgstr "Annotaties verbergen"

msgid "Hide localizer"
msgstr "Localizer verbergen"

msgid "Hide the scanogram of the current stack"
msgstr "Scanogram van de huidige stack verbergen"

msgid "Hide"
msgstr "Verbergen"

msgid "Histogram area"
msgstr "Histogramgebied"

msgid "Histogram circle"
msgstr "Histogram cirkel"

msgid "Hist. area"
msgstr "Hist. gebied"

msgid "Hist. circle"
msgstr "Hist. cirkel"

msgid "Home"
msgstr "Naar begin"

msgid "I agree"
msgstr "Ik ga akkoord"

msgid "I do not agree"
msgstr "Ik ga niet akkoord "

msgid "IDS5/web"
msgstr "IDS5/web"

msgid "Image Toolbox"
msgstr "Beeld-toolbox"

msgid "Image [cur_image,%d] of [num_images,%d]"
msgstr "Beeld [cur_image,%d] van [num_images,%d]"

msgid "Image no: [image,%d]"
msgstr "Beeldnr.: [image,%d]"

msgid "Image statistics area"
msgstr "Beeldstatistiek gebied"

msgid "Image statistics area with histogram"
msgstr "Beeldstatistiek gebied met histogram"

msgid "Image statistics circle"
msgstr "Beeldstatistiek cirkel"

msgid "Image statistics circle with histogram"
msgstr "Beeldstatistiek cirkel met histogram"

msgid "Image Viewer"
msgstr "Beeld-viewer"

msgid "Image window"
msgstr "Beeldvenster"

msgid "Image"
msgstr "Beeld"

msgid "Import status"
msgstr "Importstatus"

msgid "Incorrect password."
msgstr "Onjuist wachtwoord."

msgid "Index"
msgstr "Index"

msgid "Index..."
msgstr "Index..."

msgid "Information"
msgstr "Informatie"

msgid "Institution"
msgstr "Instelling"

msgid "Invalid input"
msgstr "Ongeldige invoer "

msgid "Invalid setting"
msgstr "Ongeldige instelling "

msgid "Invert greyscale of image"
msgstr "Grijsschaal van het beeld inverteren"

msgid "Invert"
msgstr "Inverteren"

msgid "KEY Left"
msgstr "Links"

msgid "KEY Right"
msgstr "Rechts"

msgid "Key images"
msgstr "Sleutelbeelden"

msgid "KNOWN_LIMITATIONS_TEXT"
msgstr "Visit the tech note database at Sectra User Web for information 
on known limitations and identified issues."

msgid "Label"
msgstr "Label"

msgid "Large - Fast networks"
msgstr "Grote - snelle netwerken"

msgid "Last"
msgstr "Laatste"

msgid "Less than"
msgstr "minder dan"

msgid "Level 1:"
msgstr "Niveau 1:"

msgid "Level 2:"
msgstr "Niveau 2:"

msgid "Level 3:"
msgstr "Niveau 3:"

msgid "Level 4:"
msgstr "Niveau 4:"

msgid "License check"
msgstr "Licentiecontrole "

msgid "Line down"
msgstr "Regel omlaag"

msgid "Line up"
msgstr "Regel omhoog"

msgid "Line"
msgstr "Lijn"

msgid "Ln down"
msgstr "Regel oml."

msgid "Ln up"
msgstr "Regel omh."

msgid "Local area network (10 Mb/s)"
msgstr "LAN (10 Mb/s) "

msgid "Local window"
msgstr "Lokaal venster"

msgid "Local"
msgstr "Lokaal"

msgid "Login"
msgstr "Aanmelden"

msgid "Loop selected range"
msgstr "Loop geselecteerde bereik"

msgid "Loop"
msgstr "Loop"

msgid "Ma&ximum"
msgstr "Ma&ximum"

msgid "Magnify"
msgstr "Vergroten"

msgid "Magnifying glass"
msgstr "Vergrootglas"

msgid "Mark end point of known distance"
msgstr "Eindpunt van bekende afstand markeren"

msgid "Mark start point of known distance"
msgstr "Beginpunt van bekende afstand markeren"

msgid "Max image info"
msgstr "Max. beeldinfo "

msgid "Max"
msgstr "Max."

msgid "Maximize the area used for image display"
msgstr "Gebruikte gebied voor beeldweergave maximaliseren "

msgid "Mean:"
msgstr "Gemiddelde:"

msgid "Measure angle"
msgstr "Hoek meten"

msgid "Measure area"
msgstr "Oppervlakte meten"

msgid "Measure distance"
msgstr "Afstand meten"

msgid "Measure"
msgstr "Meten"

msgid "Medium - Standard networks"
msgstr "Gemiddeld - Standaard netwerken "

msgid "Menu..."
msgstr "Menu..."

msgid "Min image info"
msgstr "Min. beeldinfo "

msgid "Min"
msgstr "Min."

msgid "Min-Max"
msgstr "Min-Max"

msgid "Min/max time:"
msgstr "Min/max tijd: "

msgid "Mismatch"
msgstr "Verkeerde combinatie"

msgid "Missing RIS info"
msgstr "RIS-info ontbreekt"

msgid "Modality"
msgstr "Modaliteit"

msgid "month"
msgstr "maand"

msgid "months"
msgstr "maanden"

msgid "Move to first frame"
msgstr "Ga naar eerste frame"

msgid "Move to last frame"
msgstr "Ga naar laatste frame"

msgid "Movie position slider"
msgstr "Schuifknop filmpositie"

msgid "&New"
msgstr "&Nieuw"

msgid "NUM ,"
msgstr "AANT ,"

msgid "NUM 0"
msgstr "AANT 0"

msgid "NUM 1"
msgstr "AANT 1"

msgid "NUM 3"
msgstr "AANT 3"

msgid "NUM 4"
msgstr "AANT 4"

msgid "NUM 6"
msgstr "AANT 6"

msgid "NUM 7"
msgstr "AANT 7"

msgid "NUM 9"
msgstr "AANT 9"

msgid "NUM+"
msgstr "AANT+"

msgid "NUM-"
msgstr "AANT-"

msgid "Name:"
msgstr "Naam:"

msgid "Neg/pos deviation:"
msgstr "Neg/pos afwijking: "

msgid "Network Test"
msgstr "Netwerktest"

msgid "Network test cancelled."
msgstr "Netwerktest geannuleerd. "

msgid "Network test failed, please try again."
msgstr "Netwerktest mislukt, probeer het opnieuw. "

msgid "Network test..."
msgstr "Netwerktest... "

msgid "Network type:"
msgstr "Netwerktype: "

msgid "Next key series"
msgstr "Volgende serie met sleutelbeeld "

msgid "Next monitor"
msgstr "Volgende monitor "

msgid "Next series"
msgstr "Volgende serie "

msgid "Next"
msgstr "Volgende"

msgid "No reports"
msgstr "Geen verslagen"

msgid "No valid IDS5/web license found on the server. Contact your server administrator for help."
msgstr "Er is geen geldige IDS5/Web-licentie gevonden op de server.  Neem contact op met uw systeembeheerder voor hulp."

msgid "No valid IDS5/web license for external integration found on the server. Contact your server administrator for help."
msgstr "Er is geen geldige IDS5/Web-licentie voor externe integratie gevonden op de server.  Neem contact op met uw systeembeheerder voor hulp."

msgid "No valid license."
msgstr "Geen geldige licentie. "

msgid "No valid search criteria found."
msgstr "Geen geldige zoekcriteria gevonden. "

msgid "No"
msgstr "Nee"

msgid "Not calibrated"
msgstr "Niet gekalibreerd"

msgid "Not equal"
msgstr "is niet "

msgid "OK"
msgstr "OK"

msgid "Open"
msgstr "Openen"

msgid "Open a DICOM package"
msgstr "DICOM-pakket openen "

msgid "Open DICOM package..."
msgstr "DICOM-pakket openen..."

msgid "Open the user's guide"
msgstr "Gebruikershandleiding openen "

msgid "Orientation"
msgstr "Stand"

msgid "Original"
msgstr "Origineel"

msgid "PARTNER_COPYRIGHT"
msgstr ""

msgid "PARTNER_STATEMENT"
msgstr ""

msgid "Page down"
msgstr "Pagina omlaag"

msgid "Page up"
msgstr "Pagina omhoog"

msgid "PageDown"
msgstr "Pagina omlaag"

msgid "PageUp"
msgstr "Pagina omhoog"

msgid "PATENT_STATEMENT"
msgstr "Protected by U.S. patents 6,005,917; 6,226,393; 6,411,729; 6,763,257; 7,162,623; 7,532,214; 7,660,461; 7,689,539; 7,830,381; 7,936,930; 7,940,270; 7,992,100; 8,051,386; 8,131,033; Japanese patent 3646122; European patents 0818971; 1046374; and 
Swedish patents 0203545; 0300951. Patents Pending in the U.S. and 
other countries."

msgid "Patient CD Index"
msgstr "Patiënt-CD-index"

msgid "Patient ID"
msgstr "Patiëntnummer"

msgid "Patient Index"
msgstr "Patiëntenindex"

msgid "Patient birthdate"
msgstr "Geboortedatum patiënt"

msgid "Patient database ID"
msgstr "Databasenr. patiënt"

msgid "Patient name"
msgstr "Naam patiënt"

msgid "Patient sex"
msgstr "Geslacht"

msgid "Pause the cine loop"
msgstr "Cine-loop pauzeren"

msgid "Performance warning"
msgstr "Prestatiewaarschuwing "

msgid "Pg down"
msgstr "Pag. oml."

msgid "Pg up"
msgstr "Pag. omh."

msgid "Physician name"
msgstr "Naam arts"

msgid "Pixel"
msgstr "Pixel"

msgid "Pixel to pixel (1:1)"
msgstr "Pixel per pixel (1:1)"

msgid "Please enter an integer."
msgstr "Voer een geheel getal in. "

msgid "Please enter an integer between %d and %d."
msgstr "Voer een geheel getal tussen %d en %d in. "

msgid "Please login by entering your user name and password."
msgstr "Meld u aan met uw gebruikersnaam en wachtwoord. "

msgid "Point"
msgstr "Punt"

msgid "Polyline"
msgstr "Meerdere lijnen"

msgid "Pos: [pos,%g]"
msgstr "Pos: [pos,%g]"

msgid "Previous key series"
msgstr "Vorige serie met sleutelbeeld "

msgid "Previous monitor"
msgstr "Vorige monitor "

msgid "Previous series"
msgstr "Vorige serie "

msgid "Previous"
msgstr "Vorige"

msgid "Print"
msgstr "Afdrukken"

msgid "Print..."
msgstr "Afdrukken..."

msgid "Print displayed images"
msgstr "Weergegeven beelden afdrukken "

msgid "Print image"
msgstr "Beeld afdrukken "

msgid "Print page"
msgstr "Pagina afdrukken"

msgid "Print page..."
msgstr "Pagina afdrukken... "

msgid "Print presentation"
msgstr "Presentatie afdrukken "

msgid "Properties"
msgstr "Eigenschappen"

msgid "Query:"
msgstr "Navraag:"

msgid "Question"
msgstr "Vraag"

msgid "Queued"
msgstr "In de wachtrij"

msgid "RE_ENGINEERING_STATEMENT"
msgstr "Het is door de wet verboden om de software of enig deel ervan te decompileren of er reverse engineering op toe te passen."

msgid "RIS ID"
msgstr "RIS-nummer"

msgid "RIS state" 
msgstr "Status"

msgid "Reading radiologist"
msgstr "Verslaand radioloog"

msgid "Referring physician"
msgstr "Verwijzende arts"

msgid "Referring unit"
msgstr "Verwijzende instantie"

msgid "Refine image"
msgstr "Beeld verfijnen "

msgid "Refine stack"
msgstr "Stack verfijnen "

msgid "Refine the quality of all images in the displayed stack"
msgstr "Kwaliteit van alle beelden in de weergegeven stack verfijnen "

msgid "Refine the quality of the displayed image"
msgstr "Kwaliteit van het weergegeven beeld verfijnen "

msgid "Refine"
msgstr "Verfijnen"

msgid "Refresh"
msgstr "Vernieuwen"

msgid "REGULATORY_NAME_IDS5/web"
msgstr "Sectra Workstation IDS5"

msgid "Release synchronization"
msgstr "Synchronisatie opheffen"

msgid "Release"
msgstr "Opheffen"

msgid "Remove the cropping of the image"
msgstr "Inkadering van het beeld verwijderen"

msgid "Remove"
msgstr "Verwijderen"

msgid "Report"
msgstr "Verslag"

msgid "Reports"
msgstr "Verslagen"

msgid "Reports are being edited. Please save or cancel all changes before performing a new search."
msgstr "Verslagen worden bewerkt.  Sla alle veranderingen op of annuleer ze voordat u een nieuwe zoekopdracht uitvoert. "

msgid "Reports are being edited. Please save or cancel all changes before exiting."
msgstr "Verslagen worden bewerkt.  Sla alle veranderingen op of annuleer ze voordat u afsluit. "

msgid "New report"
msgstr "Nieuw verslag"

msgid "Request and scanned documents"
msgstr "Aanvraag en gescande documenten "

msgid "Request number"
msgstr "Accessionnummer"

msgid "Request"
msgstr "Aanvraag"

msgid "Requests and Reports"
msgstr "Aanvragen en verslagen"

msgid "Reset any modifications to the presentation"
msgstr "Alle wijzigingen in de presentatie herstellen "

msgid "Reset calibration"
msgstr "Kalibratie herstellen"

msgid "Reset cropping"
msgstr "Inkaderen opheffen"

msgid "Reset image to default setting"
msgstr "Beeld herstellen naar standaardinstelling"

msgid "Reset image"
msgstr "Beeld herstellen"

msgid "Reset presentation"
msgstr "Presentatie herstellen "

msgid "Reset the speed to the default value"
msgstr "Snelheid herstellen naar standaardwaarde"

msgid "Reset to presentation state"
msgstr "Herstellen naar presentatiestatus"

msgid "Reset"
msgstr "Herstellen"

msgid "Response time:"
msgstr "Reactietijd: "

msgid "Retrieve"
msgstr "Ophalen"

msgid "Retrieving"
msgstr "Bezig met ophalen"

msgid "RIS report"
msgstr "RIS-verslag"

msgid "Rotate 180° clockwise"
msgstr "180° naar rechts draaien"

msgid "Rotate 180°"
msgstr "180° draaien"

msgid "Rotate 270° clockwise"
msgstr "270° naar rechts draaien"

msgid "Rotate 270°"
msgstr "270° draaien"

msgid "Rotate 90° clockwise"
msgstr "90° naar rechts draaien"

msgid "Rotate 90°"
msgstr "90° draaien"

msgid "Run the current Image Viewer (version %s)."
msgstr "Huidige Beeldviewer gebruiken (versie %s). "

msgid "Run the viewer on the CD (version %s)."
msgstr "Viewer op de CD gebruiken (versie %s). "

msgid "&Save"
msgstr "&Opslaan"

msgid "SECTRA_COPYRIGHT"
msgstr "© Sectra AB, Zweden, 2013"

msgid "STAT"
msgstr "SPOED"

msgid "SW_LICENSING_STATEMENT"
msgstr "Copyrights en alle andere eigendomsrechten in alle software en bijbehorende documentatie (""Software"") die u ter beschikking zijn gesteld, blijven het exclusieve eigendom van Sectra AB. Er wordt geen enkele aanspraak of eigendom in de Software aan u overgedragen. Gebruik van de Software is onderworpen aan de voorwaarden van de eindgebruikerslicentie, die op verzoek verkrijgbaar zijn."

msgid "Save"
msgstr "Opslaan"

msgid "Save as"
msgstr "Opslaan als"

msgid "Scanned doc "
msgstr "Gescand document "

msgid "Scanogram"
msgstr "Scanogram"

msgid "Scheduled"
msgstr "Gepland"

msgid "Scroll"
msgstr "Schuiven"

msgid "Search criteria are not specific enough."
msgstr "Zoekcriteria zijn niet specifiek genoeg. NB: Zoeken op datum is alleen mogelijk met begrensde intervallen."

msgid "Search for cases to view"
msgstr "Zoeken naar casussen om te bekijken "

msgid "Search"
msgstr "Zoeken"

msgid "Search..."
msgstr "Zoeken..."

msgid "Searching, please wait..."
msgstr "Bezig met zoeken, even geduld... "

msgid "Sectra Homepage"
msgstr "Sectra-homepage"

msgid "Sectra Image Viewer"
msgstr "Beeld-viewer"

msgid "Sectra"
msgstr "Sectra"

msgid "Select network type:"
msgstr "Selecteer netwerktype: "

msgid "Select this button to enable higher cine loop speed. This will temporarily hide image information."
msgstr "Selecteer deze knop om een hogere cine-loopsnelheid in te stellen. Hierdoor wordt beeldinformatie tijdelijk verborgen."

msgid "Select this button to use lower image quality to enable higher cine loop speed."
msgstr "Selecteer deze knop voor een lagere beeldkwaliteit ten behoeve van een hogere cine-loopsnelheid."

msgid "Sending"
msgstr "Bezig met verzenden"

msgid "Seq: [seq_name]"
msgstr "Seq: [seq_name]"

msgid "Server:"
msgstr "Server:"

msgid "Set range start position"
msgstr "Bereik startpositie instellen "

msgid "Set range stop position"
msgstr "Bereik stoppositie instellen"

msgid "Shift+PageDown"
msgstr "Shift+Pagina omlaag"

msgid "Shift+PageUp"
msgstr "Shift+Pagina omhoog"

msgid "Show &reports automatically"
msgstr "&Verslagen automatisch tonen "

msgid "Show DICOM overlays (&black)"
msgstr "DICOM-overlays tonen (&zwart)"

msgid "Show DICOM overlays (&white)"
msgstr "DICOM-overlays tonen (&wit)"

msgid "Show DICOM overlays (black)"
msgstr "DICOM-overlays tonen (zwart)"

msgid "Show DICOM overlays (white)"
msgstr "DICOM-overlays tonen (wit)"

msgid "Show W/L control"
msgstr "V/N-regeling tonen"

msgid "Show all available localizer lines, excluding crosshair marker"
msgstr "Alle beschikbare localizer-lijnen tonen, zonder kruiscursor"

msgid "Show all available localizer lines, including crosshair marker"
msgstr "Alle beschikbare localizer-lijnen tonen, inclusief kruiscursor"

msgid "Show all controls"
msgstr "Alle regelingen tonen "

msgid "Show an index of all cases in the file"
msgstr "Een index van alle casussen in het bestand tonen "

msgid "Show an index of all cases on the patient CD"
msgstr "Een index van alle casussen op de patiënt-CD tonen "

msgid "Show annotations"
msgstr "Annotaties tonen"

msgid "Show control for scrolling in stacks"
msgstr "Schuifregeling voor stacks tonen"

msgid "Show control for windowing operations"
msgstr "Regeling voor vensterbewerkingen tonen"

msgid "Show control for zoom operations"
msgstr "Regelingen voor zoombewerkingen tonen"

msgid "Show localizer"
msgstr "Localizer tonen"

msgid "Show menu"
msgstr "Menu tonen"

msgid "Show performance warning before loading full DICOM quality."
msgstr "Prestatiewaarschuwing tonen alvorens volledige DICOM-kwaliteit te laden. "

msgid "Show properties for the selected examination"
msgstr "Eigenschappen voor het geselecteerde onderzoek tonen "

msgid "Show pixel value"
msgstr "Pixelwaarde tonen"

msgid "Show the value of the single pixel under the pointer"
msgstr "Geef de waarde weer van de ene pixel onder de aanwijzer"

msgid "Show reports..."
msgstr "Verslagen tonen..."

msgid "Show requests, scanned documents and reports"
msgstr "Aanvragen, gescande documenten en verslagen tonen "

msgid "Show scroll control"
msgstr "Schuifregeling tonen"

msgid "Show simple localizer"
msgstr "Eenvoudige localizer tonen"

msgid "Show simple"
msgstr "Eenvoudig tonen"

msgid "Show the next key image in the examination"
msgstr "Volgende sleutelbeeld in het onderzoek tonen "

msgid "Show the next monitor in the presentation"
msgstr "Volgende monitor in de presentatie tonen "

msgid "Show the next series in the examination"
msgstr "Volgende serie in het onderzoek tonen "

msgid "Show the previous key image in the examination"
msgstr "Vorige sleutelbeeld in het onderzoek tonen "

msgid "Show the previous monitor in the presentation"
msgstr "Vorige monitor in de presentatie tonen "

msgid "Show the previous series in the examination"
msgstr "Vorige serie in het onderzoek tonen "

msgid "Show the scanogram of the current stack"
msgstr "Scanogram van de huidige stack tonen"

msgid "Show zoom control"
msgstr "Zoomregeling tonen"

msgid "Show"
msgstr "Weergeven"

msgid "Signatures"
msgstr "Handtekeningen"

msgid "Slice: [slice,%g] mm"
msgstr "Snede: [slice,%g] mm"

msgid "Small - Slow networks"
msgstr "Kleine - Langzame netwerken"

msgid "Some of the selected examinations are currently not available for viewing. Do you want to open the search dialog in order to retrieve them from the archive?"
msgstr "Sommige van de geselecteerde onderzoeken kunnen op dit moment niet bekeken worden.  Wilt u het zoekdialoogvenster openen om ze op te halen uit het archief? "

msgid "Speed: "
msgstr "Snelheid: "

msgid "Stack navigation"
msgstr "Stack-navigatie"

msgid "Stack tile"
msgstr "Stack-tegel"

msgid "Start animation of all images in stack"
msgstr "Animatie starten van alle beelden in de stack"

msgid "Start bouncing animation of all images in stack"
msgstr "Bouncing animatie starten van alle beelden in de stack"

msgid "Start the cine loop"
msgstr "Cine-loop starten "

msgid "Start"
msgstr "Begin"

msgid "Starting retrieval from archive..."
msgstr "Ophalen uit archief wordt gestart... "

msgid "Station name"
msgstr "Naam station"

msgid "Statistics ar&ea"
msgstr "Statistiek ge&bied"

msgid "Statistics c&ircle"
msgstr "Statistiek c&irkel"

msgid "Status"
msgstr "Status"

msgid "Step W/L"
msgstr "V/N doorlopen"

msgid "Step back one frame"
msgstr "Eén frame terug gaan "

msgid "Step forward one frame"
msgstr "Eén frame vooruit gaan"

msgid "Step through local window settings"
msgstr "Lokale vensterinstellingen doorlopen"

msgid "Stop cine loop"
msgstr "Animatieloop stoppen"

msgid "Stop cine"
msgstr "Cine stoppen"

msgid "Stop"
msgstr "Stoppen"

msgid "Study Instance UID"
msgstr "Instance UID van onderzoek"

msgid "Sync"
msgstr "Synch"

msgid "Synchronize operations with other synchronized images/stacks"
msgstr "Bewerkingen met andere gesynchroniseerde beelden/stacks synchroniseren"

msgid "Synchronize"
msgstr "Synchroniseren"

msgid "T1 line (512 kb/s)"
msgstr "T1-lijn (512 kb/s) "

msgid "TE: [echo_time,%g]"
msgstr "TE: [echo_time,%g]"

msgid "TR: [rep_time,%g]"
msgstr "TR: [rep_time,%g]"

msgid "Test result:"
msgstr "Testresultaat: "

msgid "Test the performance of the network"
msgstr "Prestaties van het netwerk testen "

msgid "Test to perform:"
msgstr "Uit te voeren test: "

msgid "Test"
msgstr "Test"

msgid "Testing, %.0lf%s done..."
msgstr "Bezig met testen, %.0lf%s gereed... "

msgid "Text"
msgstr "Tekst"

msgid "The application will shut down. You have unsaved report changes. Do you wan't to save these changes?"
msgstr "De toepassing wordt afgesloten.  U heeft niet-opgeslagen veranderingen in uw verslag.  Wilt u deze veranderingen opslaan? "

msgid "The Internet Explorer option 'Automatically detect settings' is enabled. This setting will impact client performance severely. Do you wish to disable this setting?"
msgstr "De optie van Internet Explorer 'Instellingen automatisch detecteren' is ingeschakeld.  Deze instelling is sterk van invloed op de prestaties van de client.  Wilt u deze instelling uitschakelen? "

msgid "The Viewer was started with invalid search criteria."
msgstr "De Viewer is gestart met ongeldige zoekcriteria. "

msgid "The call is not supported by the server."
msgstr "De oproep wordt niet ondersteund door de server. "

msgid "The compression setting for level 2 must be inbetween levels 1 and 3."
msgstr "De compressie-instelling voor niveau 2 moet tussen niveau 1 en 3 liggen. "

msgid "The new password is invalid. Please avoid special characters like space and %s in the password."
msgstr "Het nieuwe wachtwoord is ongeldig. Gebruik de volgende speciale tekens of spaties niet: %s"

msgid "The password has expired. Please change it to login."
msgstr "Het wachtwoord is verlopen.  Verander uw wachtwoord om u aan te melden. "

msgid "The passwords you typed do not match."
msgstr "De wachtwoorden die u heeft ingetypt komen niet overeen."

msgid "The server has started retrieving the selected examination(s) from the archive. Please wait a while and then press the '%s' button repeatedly until the examinations have become available."
msgstr "De server is gestart met het ophalen van de geselecteerde onderzoek(en) uit het archief.  Wacht even en druk meerdere malen op de '%s'-knop tot de onderzoeken beschikbaar zijn. "

msgid "There are too many clients connected. Please try again later."
msgstr "Er zijn te veel clients aangesloten. Probeer het op een later tijdstip opnieuw."

msgid "There are still unsaved reports. Please save or cancel all changes before closing the report dialog."
msgstr "Er zijn nog niet-opgeslagen verslagen.  Sla alle veranderingen op of annuleer ze voordat u het dialoogvenster verslaglegging sluit. "

msgid "This DICOM-folder is not exported by a Sectra PACS, or the contents have been modified. Exiting application."
msgstr "Deze DICOM-map is niet geëxporteerd door een Sectra PACS, of de inhoud ervan is gewijzigd.  Toepassing wordt afgesloten. "

msgid "This list shows all the examinations in the patient file. Select one or more (Ctrl + click) examinations for a patient and press OK to view the images."
msgstr "Deze lijst geeft alle onderzoeken in het patiëntbestand weer.  Selecteer één of meer (Ctrl + klik) onderzoeken voor een patiënt en druk op OK om de beelden te bekijken. "

msgid "This list shows all the examinations on the patient CD. Select one or more (Ctrl + click) examinations for a patient and press OK to view the images."
msgstr "Deze lijst geeft alle onderzoeken op de patiënt-CD weer.  Selecteer één of meer (Ctrl + klik) onderzoeken voor een patiënt en druk op OK om de beelden te bekijken. "

msgid "This list shows the examinations that matched the search criteria. Select one or more (Ctrl + click) examinations for a patient and press OK to view the images."
msgstr "Deze lijst geeft de onderzoeken die overeenkomen met de zoekcriteria.  Selecteer één of meer (Ctrl + klik) onderzoeken voor een patiënt en druk op OK om de beelden te bekijken. "

msgid "Throughput:"
msgstr "Verwerkt: "

msgid "Tile 1x1"
msgstr "Tegel 1x1"

msgid "Tile 2x2"
msgstr "Tegel 2x2"

msgid "Tile 3x3"
msgstr "Tegel 3x3"

msgid "Tile 4x4"
msgstr "Tegel 4x4"

msgid "Tile"
msgstr "Tegel"

msgid "Time: [time,%d] ms"
msgstr "Tijd: [time,%d] ms "

msgid "Toggle PS"
msgstr "PS wisselen"

msgid "Toggle between previous image state and the latest crop"
msgstr "Wisselen tussen vorige beeldstatus en laatste inkadering"

msgid "Toggle between settings from a DICOM presentation state and image reset"
msgstr "Wisselen tussen instellingen van een DICOM-presentatiestatus en beeld herstellen "

msgid "Toggle crop state"
msgstr "Wisselen tussen inkadering"

msgid "Toggle presentation state"
msgstr "Presentatiestatus wisselen "

msgid "Toggle"
msgstr "Wisselen"

msgid "Too many results; try narrowing your search."
msgstr "Te veel resultaten; probeer uw zoekcriteria aan te passen. "

msgid "Tool controls"
msgstr "Toolregelingen "

msgid "Total time:"
msgstr "Totale tijd: "

msgid "True (empty)"
msgstr "Waar (leeg) "

msgid "Tumour tissue"
msgstr "Tumorweefsel"

msgid "Turn off ecg"
msgstr "ECG uitschakelen"

msgid "Turn on ecg"
msgstr "ECG inschakelen"

msgid "Undefined"
msgstr "Onbepaald"

msgid "Unknown user."
msgstr "Gebruiker onbekend. "

msgid "Unknown"
msgstr "Onbekend"

msgid "User does not have permission to log in from this application"
msgstr "Gebruiker heeft geen toestemming om zich vanuit deze toepassing aan te melden"

msgid "Update"
msgstr "Updaten"

msgid "User's guide..."
msgstr "Gebruikershandleiding..."

msgid "User:"
msgstr "Gebruiker:"

msgid "Value:"
msgstr "Waarde:"

msgid "Version:"
msgstr "Versie:"

msgid "Version conflict"
msgstr "Versieconflict"

msgid "Version handling"
msgstr "Versiebeheer "

msgid "W/L"
msgstr "V/N"

msgid "Warning! Image recalibrated."
msgstr "Beeld handmatig gekalibreerd."

msgid "Warning"
msgstr "Waarschuwing"

msgid "week"
msgstr "week"

msgid "weeks"
msgstr "weken"

msgid "What am I running?"
msgstr "Wat is er actief?"

msgid "White brain substance"
msgstr "Witte hersensubstantie"

msgid "White"
msgstr "Wit"

msgid "Window/Level"
msgstr "Venster/Niveau"

msgid "Write distance in mm."
msgstr "Typ afstand in (in mm)."

msgid "Write text"
msgstr "Tekst intypen"

msgid "&Worklists:"
msgstr "&Werklijsten: "

msgid "Year of release:"
msgstr "Jaar van uitgave:"

msgid "year"
msgstr "jaar"

msgid "years"
msgstr "jaren"

msgid "Yes"
msgstr "Ja"

msgid "You are currently running version %s of the Image Viewer. The CD is exported by IDS5 version %s. It is recommended that you download the latest version of the Image Viewer or that you use the viewer on the CD, since it might have features that the current version does not support."
msgstr "U gebruikt op dit moment versie %s van de Beeldviewer.  De CD is geëxporteerd door IDS5 versie %s.  Het wordt aanbevolen om de nieuwste versie van de Beeldviewer te downloaden of de viewer op de CD te gebruiken, omdat deze mogelijk functies heeft die niet ondersteund worden door de huidige versie. "

msgid "You are currently running version %s of the Image Viewer. The CD is exported by IDS5 version %s. You are required to run version %s or newer to be able to view the contents of the CD."
msgstr "U gebruikt op dit moment versie %s van de Beeldviewer.  De CD is geëxporteerd door IDS5 versie %s.  U dient versie %s of hoger te gebruiken om de inhoud van de CD te kunnen bekijken. "

msgid "You are currently running version %s of the Image Viewer. The DICOM package is exported by IDS5 version %s. It is recommended that you download the latest version of the Image Viewer, since it might have features that the current version does not support."
msgstr "U gebruikt op dit moment versie %s van de Beeldviewer.  Het DICOM-pakket is geëxporteerd door IDS5 versie %s.  Het wordt aanbevolen om de nieuwste versie van de Beeldviewer te downloaden of de viewer op de CD te gebruiken, omdat deze mogelijk functies heeft die niet ondersteund worden door de huidige versie. "

msgid "You are currently running version %s of the Image Viewer. The DICOM package is exported by IDS5 version %s. You are required to run version %s or newer to be able to view the contents of the DICOM package."
msgstr "U gebruikt op dit moment versie %s van de Beeldviewer.  Het DICOM-pakket is geëxporteerd door IDS5 versie %s.  U dient versie %s of hoger te gebruiken om de inhoud van het DICOM-pakket te kunnen bekijken. "

msgid "You must enter a name, please try again."
msgstr "U moet een naam invoeren; probeer het opnieuw."

msgid "Zoom in"
msgstr "Inzoomen"

msgid "Zoom out"
msgstr "Uitzoomen"

msgid "Zoom pixel to pixel"
msgstr "Pixel per pixel zoomen (1:1) "

msgid "Zoom to fit the screen exactly"
msgstr "Precies passend in scherm zoomen"

msgid "Zoom to fit window"
msgstr "Passend in venster zoomen"

msgid "Zoom to true size"
msgstr "Naar ware grootte zoomen"

msgid "Zoom"
msgstr "Zoomen"

msgid "[Thickness,%g]mm, Dose: [organ_dose,%.2g]dGy, [kV,%g]kV, [mAs,%d]mAs"
msgstr "[Thickness,%g]mm, Dosis: [organ_dose,%.2g]dGy, [kV,%g]kV, [mAs,%d]mAs"

msgid "[date,,.,,$(0)], [station_name]"
msgstr "[date,,.,,$(0)], [station_name]"

msgid "[date,,.,,$(0)], [time,,:,,$(1)$(2):$(3)$(4)]"
msgstr "[date,,.,,$(0)], [time,,:,,$(1)$(2):$(3)$(4)]"

msgid "[group]"
msgstr "[group]"

msgid "[id]"
msgstr "[id]"

msgid "[image_laterality] [view_position] [spot_compression]"
msgstr "[image_laterality] [view_position] [spot_compression]"

msgid "[image_order,%d]"
msgstr "[image_order,%d]"

msgid "[kvp,%g] kV"
msgstr "[kvp,%g] kV"

msgid "[ma,%d] mA"
msgstr "[ma,%d] mA"

msgid "[name]"
msgstr "[name]"

msgid "[pat_pos]"
msgstr "[pat_pos]"

msgid "[pos_label,%s]"
msgstr "[pos_label,%s]"

msgid "fps"
msgstr "fps"

msgid "hounsfield Stat"
msgstr "Statistische gegevens"

msgid "image loading error"
msgstr "Fout"

msgid "is defined"
msgstr "is gedefinieerd"

msgid "is undefined"
msgstr "is niet gedefinieerd"

msgid "kB/s"
msgstr "kB/s"

msgid "ms"
msgstr "ms"

msgid "no images"
msgstr ""

msgid "s"
msgstr "s"

msgid "version"
msgstr "versie"

msgid "x"
msgstr "x"

msgid "Pan"
msgstr "Pannen"

msgid "Browse"
msgstr "Bladeren"

msgid "Rotate"
msgstr "Draaien"

msgid "Zoom_im"
msgstr "Zoomen"

msgid "Next status"
msgstr "Volgende status"

msgid "Set status"
msgstr "Status instellen"

msgid "Set next status of the examination"
msgstr "Volgende status van het onderzoek instellen "

msgid "Set status of the examination"
msgstr "Status van het onderzoek instellen "

msgid "Select the desired status from the list below and press Ok to set the state for the current examination."
msgstr "Selecteer de gewenste status uit de onderstaande lijst en druk op OK om de status voor het huidige onderzoek in te stellen. " 

msgid "Wise server: "
msgstr "WISE server: "

msgid "The examination has been changed in the database. "
msgstr "Het onderzoek is veranderd in de database.  "

msgid "The status operation was aborted. " 
msgstr "De statusbewerking is afgebroken.  " 

msgid "Please reload the examination and try again."
msgstr "Laad het onderzoek opnieuw en probeer het nogmaals. "

msgid "Set status operation failed."
msgstr "Statusbewerking instellen mislukt.  Er is een fout opgetreden. "

msgid "Changing status, please wait..."
msgstr "Bezig met veranderen van de status, even geduld a.u.b. ... "

msgid "Close"
msgstr "Sluiten"

msgid "Play sound report"
msgstr "Geluidsverslag afspelen"

msgid "Stop current action"
msgstr "Huidige actie stoppen"

msgid "Rewind to beginning"
msgstr "Terugspoelen naar begin"

msgid "Failed to retrieve sound. Sound file may be missing."
msgstr "Geluid ophalen mislukt. Mogelijk ontbreekt het geluidsbestand."

msgid "Open image windows"
msgstr "Beeldvensters openen"

msgid "Open or close additional image windows"
msgstr "Aanvullende beeldvensters openen of sluiten"

msgid "Main window - Sectra Image Viewer"
msgstr "Hoofdvenster - Sectra beeld-viewer"


#attribute definite form 
msgid "attribute"   
msgstr "kenmerk"

msgid "over the"
msgstr "over de"

msgid  "Pixel Spacing"
msgstr "Pixeltussenruimte"

msgid  "Imager Pixel Spacing"
msgstr "Pixeltussenruimte beeldvormer"

msgid  "Manual calibration"
msgstr "Handmatige kalibratie"

msgid  "Estimated Radiographic Magnification Factor"
msgstr "Geschatte radiografische vergrotingsfactor "

msgid  "based on the"
msgstr "gebaseerd op de"

msgid  "Ultrasound Delta"
msgstr "Delta van echografie"

msgid  "measurement"
msgstr "meting"

msgid "Area:"
msgstr "Oppervlakte:"

msgid "Max:"
msgstr "Max.:"

msgid "Pixels:"
msgstr "Pixels:"

msgid "Total:"
msgstr "Totaal:"

msgid "NM Statistics area"
msgstr "NM-statistiek gebied"

msgid "NM Stat. area"
msgstr "NM St. gebied"

msgid "THINSTALL_STATEMENT"
msgstr "Aangedreven door Thinstall.  Gedeelten van deze software bevatten Thinstall technologie. Copyright © 1999-2005 Jitit.  Alle rechten voorbehouden."



